{{- if .Values.enforcer.enabled -}}
{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: DaemonSet
metadata:
  name: neuvector-enforcer-pod
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  updateStrategy: {{- toYaml .Values.enforcer.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      app: neuvector-enforcer-pod
  template:
    metadata:
      labels:
        app: neuvector-enforcer-pod
        release: {{ .Release.Name }}
        {{- with .Values.enforcer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.enforcer.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
    {{- end }}
    {{- if .Values.enforcer.tolerations }}
      tolerations:
{{ toYaml .Values.enforcer.tolerations | indent 8 }}
    {{- end }}
      hostPID: true
    {{- if .Values.enforcer.priorityClassName }}
      priorityClassName: {{ .Values.enforcer.priorityClassName }}
    {{- end }}
    {{- if .Values.leastPrivilege }}
      serviceAccountName: enforcer
      serviceAccount: enforcer
    {{- else }}
      serviceAccountName: {{ .Values.serviceAccount }}
      serviceAccount: {{ .Values.serviceAccount }}
    {{- end }}
      containers:
        - name: neuvector-enforcer-pod
          {{- if .Values.global.azure.enabled }}
          image: "{{ .Values.global.azure.images.enforcer.registry }}/{{ .Values.global.azure.images.enforcer.image }}@{{ .Values.global.azure.images.enforcer.digest }}"
          {{- else }}
          {{- if eq .Values.registry "registry.neuvector.com" }}
          {{- if .Values.oem }}
          image: "{{ .Values.registry }}/{{ .Values.oem }}/enforcer:{{ .Values.tag }}"
          {{- else }}
          image: "{{ .Values.registry }}/enforcer:{{ .Values.tag }}"
          {{- end }}
          {{- else }}
          {{- if .Values.enforcer.image.hash }}
          image: "{{ .Values.registry }}/{{ .Values.enforcer.image.repository }}@{{ .Values.enforcer.image.hash }}"
          {{- else }}
          image: "{{ .Values.registry }}/{{ .Values.enforcer.image.repository }}:{{ .Values.tag }}"
          {{- end }}
          {{- end }}
          {{- end }}
          securityContext:
            privileged: true
          resources:
          {{- if .Values.enforcer.resources }}
{{ toYaml .Values.enforcer.resources | indent 12 }}
          {{- else }}
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
          env:
            - name: CLUSTER_JOIN_ADDR
              value: neuvector-svc-controller.{{ .Release.Namespace }}
            - name: CLUSTER_ADVERTISED_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CLUSTER_BIND_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- with .Values.enforcer.env }}
{{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if regexMatch "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+[0-9A-Za-z-]+)?$" .Values.tag }}
            {{- if semverCompare "<5.3.0" .Values.tag }}
              {{- if eq .Values.containerRuntime.runTimePath "auto" }}
            - mountPath:  {{ include "helper.runtime" . | toString }}
              name: runtime-sock
              readOnly: true
            - mountPath: /host/proc
              name: proc-vol
              readOnly: true
            - mountPath: /host/cgroup
              name: cgroup-vol
              readOnly: true
            {{- end }}
            {{- end }}
          {{- else if .Values.containerRuntime }}
            # test: "runtime jaime"
            {{- if ne .Values.containerRuntime.runTimePath "auto" }}
            - mountPath: /run/runtime.sock
              name: runtime-sock
              readOnly: true  
            {{ end }}
          {{- end }}
            - mountPath: /lib/modules
              name: modules-vol
              readOnly: true
            - mountPath: /var/nv_debug
              name: nv-debug
              readOnly: false
          {{- if .Values.internal.certmanager.enabled }}
            - mountPath: /etc/neuvector/certs/internal/cert.key
              subPath: {{ .Values.enforcer.internal.certificate.keyFile }}
              name: internal-cert
              readOnly: true
            - mountPath: /etc/neuvector/certs/internal/cert.pem
              subPath: {{ .Values.enforcer.internal.certificate.pemFile }}
              name: internal-cert
              readOnly: true
            - mountPath: /etc/neuvector/certs/internal/ca.cert
              subPath: {{ .Values.enforcer.internal.certificate.caFile }}
              name: internal-cert
              readOnly: true
          {{- end }}
      terminationGracePeriodSeconds: 1200
      restartPolicy: Always
      volumes:
        {{- if regexMatch "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+[0-9A-Za-z-]+)?$" .Values.tag }}
          {{- if semverCompare "<5.3.0" .Values.tag }}
            {{- if eq .Values.containerRuntime.runTimePath "auto" }}
        - name: runtime-sock
          hostPath:
            path: {{ include "helper.runtime" . | toString }}
        - name: proc-vol
          hostPath:
            path: /proc
        - name: cgroup-vol
          hostPath:
            path: /sys/fs/cgroup
            {{- end }}
      {{- else if .Values.containerRuntime }}
        {{- if ne .Values.containerRuntime.runTimePath "auto" }}
        - name: runtime-sock
          hostPath:
            path: {{ .Values.containerRuntime.runTimePath }}
        {{- end }}
      {{- end }}
      {{- end }}
        - name: modules-vol
          hostPath:
            path: /lib/modules
        - name: nv-debug
          hostPath:
            path: /var/nv_debug
      {{- if .Values.internal.certmanager.enabled }}
        - name: internal-cert
          secret:
            secretName: {{ .Values.enforcer.internal.certificate.secret }}
      {{- end }}
{{- end }}
